server:
  #端口号
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://192.168.1.106:3306/test
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.myd.entity
logging:
  level:
    com.myd.dao:  debug

